### ISSUE TITLE
Mofibo not works

### ISSUE THREAD

**Issue by phil0x1** [jo1gi/grawlix#14]

**Comment by jo1gi** [comment]
Could you give some more details. Which book? What command did you use? What is the output?

**Comment by phil0x1** [comment]
I used "Harry Potter og De Vises Sten" on Mofibo, and I also tried several other books, all of which failed to work. The main issue was that the source wasn't recognized. I also attempted Storytel in Germany, encountering the same problem. Nextory presented the same error as Mofibo and Storytel. Finally, I tried saxo(dot)com/dk, which worked for about 70% of the ebooks, but many weren't recognized and failed to load/(most newer publications) 

Nextory & Mofibo/Storytel: Similar error 

grawlix --username ******** --password ******** url
-
ERROR: The given url does not match any sources

Please make sure the link goes to the ebook you want to download and the site is
supported by grawlix. Try the link to the reader page if available.

/// Saxo(dot)com/dk

Traceback (most recent call last):
  File "/home/**/.local/bin/grawlix", line 8, in <module>
    sys.exit(run())
  File "/home/**/.local/lib/python3.10/site-packages/grawlix/__main__.py", line 150, in run
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/**/.local/lib/python3.10/site-packages/grawlix/__main__.py", line 102, in main
    result = await source.download(url)
  File "/home/**/.local/lib/python3.10/site-packages/grawlix/sources/saxo.py", line 40, in download
    book_id = await self._get_book_id(isbn)
  File "/home/**/.local/lib/python3.10/site-packages/grawlix/sources/saxo.py", line 69, in _get_book_id
    return response.json()["items"][0]["bookId"]
IndexError: list index out of range

**Comment by jo1gi** [comment]
Looks like the Storytel api has changed. It will have to be reimplemented.

**Comment by mehmetckahriman** [comment]
same issue but audiobook-dl works well 

grawlix --username ******** --password ******** https://www.storytel.com/tr/books/martin-eden-1288744
ERROR: The given url does not match any sources

Please make sure the link goes to the ebook you want to download and the site is
supported by grawlix. Try the link to the reader page if available.

**Comment by fedeD84** [comment]
Any update?

**Comment by nonab** [comment]
> Any update?

what error you get?
i tried but i wasn't able to reproduce it
i mean i get a different error

`KeyError: 'Location'`

i run it this way: 
`python -m grawlix --username *** --password *** url`
