### ISSUE TITLE
[internetarchive] ValueError: unknown url type: '/None'

### ISSUE THREAD

**Issue by metaphysicsIO** [jo1gi/grawlix#17]
I have tried surrounding the URL with quotations and without. 

Here is my terminal, I've removed personal identifiers:
```
$ grawlix --username "REDACTED" --password "REDACTED" https://archive.org/details/cruinnscrobhnaga0000macm
Authenticating with source Internet Archive
Traceback (most recent call last):
  File "/usr/bin/grawlix", line 33, in <module>
    sys.exit(load_entry_point('grawlix==0.2.0', 'console_scripts', 'grawlix')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/grawlix/__main__.py", line 150, in run
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/grawlix/__main__.py", line 102, in main
    result = await source.download(url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/grawlix/sources/internet_archive.py", line 78, in download
    metadata, acsm_file = await asyncio.gather(
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/grawlix/sources/internet_archive.py", line 108, in _download_metadata
    metadata_response = await self._client.get(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/httpx/_client.py", line 1801, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/httpx/_client.py", line 1561, in request
    request = self.build_request(
              ^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/httpx/_client.py", line 357, in build_request
    return Request(
           ^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/httpx/_models.py", line 336, in __init__
    Cookies(cookies).set_cookie_header(self)
  File "/home/USERNAME/.local/lib/python3.11/site-packages/httpx/_models.py", line 1046, in set_cookie_header
    urllib_request = self._CookieCompatRequest(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/.local/lib/python3.11/site-packages/httpx/_models.py", line 1182, in __init__
    super().__init__(
  File "/usr/lib/python3.11/urllib/request.py", line 322, in __init__
    self.full_url = url
    ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 348, in full_url
    self._parse()
  File "/usr/lib/python3.11/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/None'
```

**Comment by jo1gi** [comment]
Should be fixed in 465abbe.
