### ISSUE TITLE
Add DC Universe Infinite Source

### ISSUE THREAD

**Issue by jo1gi** [jo1gi/grawlix#4]

**Comment by rainrdx** [comment]
Coming from the audiobook side and notice this. Seems you are the only one working on DC Universe and Scribd support. Truly thank you for what you do!

**Comment by jo1gi** [comment]
I had some hacky code I got working for Dc Universe Infinite, but I can't use my account anymore to get the rest working, since all my payment methods are blocked (European cards aren't allowed).

**Comment by rainrdx** [comment]
> I had some hacky code I got working for Dc Universe Infinite, but I can't use my account anymore to get the rest working, since all my payment methods are blocked (European cards aren't allowed).

Happy to provide a trial account and if needed have no problem keeping paying for it

**Comment by jo1gi** [comment]
Thanks. That would be nice. I don't have time to work on it before 2024. Hope that's ok.

**Comment by rainrdx** [comment]
> Thanks. That would be nice. I don't have time to work on it before 2024. Hope that's ok.

Ah of course! This is holiday season and this is free work you do (already appreciate the audiobook side). Just lemme know how I can get in touch when you are in the mood for it.

**Comment by rainrdx** [comment]
Just a note that you can find me at cmR4QGxpdmUuY29t (base64) and I will delete this after I get your email.

**Comment by jo1gi** [comment]
I have created initial support. There are still are a few problems. It's on the `dcuniverseinfinite` branch.

**Comment by rainrdx** [comment]
Thank you so much. This seems to work so perfectly. Once the trial expires I will take a look at maybe subscribing to ultra.

**Comment by rainrdx** [comment]
Thank you for maintaining this. Seems there is another error now:

Traceback (most recent call last):
  File "/home/ubuntu/Github/grawlix/.grawlix/bin/grawlix", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/ubuntu/Github/grawlix/.grawlix/lib/python3.12/site-packages/grawlix/__main__.py", line 164, in run
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/Github/grawlix/.grawlix/lib/python3.12/site-packages/grawlix/__main__.py", line 120, in main
    await download_with_progress(result, progress, template)
  File "/home/ubuntu/Github/grawlix/.grawlix/lib/python3.12/site-packages/grawlix/__main__.py", line 158, in download_with_progress
    await download_book(book, update_function, template)
  File "/home/ubuntu/Github/grawlix/.grawlix/lib/python3.12/site-packages/grawlix/output/__init__.py", line 27, in download_book
    location = format_output_location(book, output_format, template)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Github/grawlix/.grawlix/lib/python3.12/site-packages/grawlix/output/__init__.py", line 47, in format_output_location
    values = { key: remove_unwanted_chars(value) for key, value in book.metadata.as_dict().items() }
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Github/grawlix/.grawlix/lib/python3.12/site-packages/grawlix/output/__init__.py", line 75, in remove_unwanted_chars
    return remove_strings(input, "/")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Github/grawlix/.grawlix/lib/python3.12/site-packages/grawlix/output/__init__.py", line 61, in remove_strings
    input = input.replace(c, "")
            ^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'replace'

My cookies are as follows and please feel free to keep it yourself:

https://pastebin.com/KPNer3wt
